# Configuration for labels
labelWip: "WIP":
  name: "WIP"
  color: "#FBCA04"

labelUnreviewed: 
  name: "Unreviewed"
  color: "#00CA04"
  
labelApproved: 
  name: "Approved"
  color: "#0E8A16"
  
labelChangesRequested:
  name: "Changes requested"
  color: "#C2E0C6"
  
labelMerged: 
  name: "Merged"
  color: "#6F42C1"

# Set to true to add "WIP" label when title is prefixed as being WIP
addWipLabel: true

# Set to true to add labels for assignees to pull requests
addAssignees: true

# A list of assignees whose names should be added as tags to PRs (Github username)
reviewers:
  - orhan:
      name: "Orhan"
      color: "#000"
      
# Custom rules that apply labels if certain conditions are met ($title will check for the PR title)
customRules:
  - "{{title}}.indexOf('[') !== 0":
      name: "Off Scope"
      color: "#FF0"
  - "{{title}}.indexOf('[HOTFIX]') === 0":
      name: "Hotfix"
      color: "#F00"
  
  